### ISSUE TITLE
Added fix for Submit date format for (mm-dd-yyyy and dd-mm-yyyy) format dates

### ISSUE THREAD

**Issue by napsteraniket** [IckleChris/jquery-date-dropdowns#11]
Hi Chris , this is a very good plugin. I have added few more enhancement for some date formats. Please Review those changes and reply me if these are fine on :-  aniket.1121@gmail.com

![jqueryfix](https://cloud.githubusercontent.com/assets/9950519/13644686/258f5ad0-e64d-11e5-8d7d-3cd9ae7792fb.JPG)

**Comment by IckleChris** [comment]
Closed as this is no longer relevant (see [2a7dfe780b](https://github.com/IckleChris/jquery-date-dropdowns/commit/2a7dfe780b9275c12f5ed3b75a1ee67c9d664693))
