### ISSUE TITLE
No "required" option

### ISSUE THREAD

**Issue by pensierinmusica** [IckleChris/jquery-date-dropdowns#6]
Thanks for putting this nice plugin together!

I noticed currently there is no option to make the date input `required`.

I know the final input that collects the entire date is of `type="hidden"` and as such it can't be `required` [according to the standards](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input).

On the other hand, it would be useful to figure out a way around this. For example the validation could be done through JavaScript inside the plugin, and in case some value is missing the plugin can mark the parent form as `invalid` or emit a custom event.

Thoughts?

**Comment by pensierinmusica** [comment]
Btw, this might help:
http://stackoverflow.com/questions/6048710/can-i-apply-the-required-attribute-to-select-fields-in-html5

We could put the `required` attribute directly on the `select` items. It should work as long as the placholder option has an empty value. Here is a code example:

``` html
<select class="month" name="date_[month] required">
<option value="">Month</option>
<option value="01">Jan</option>
<option value="02">Feb</option>
...
```

Do you think this should work?

**Comment by IckleChris** [comment]
Thanks for this, hadn't considered required fields!

The above seems more sane than attempting to validate via the JS so I'm good with that solution. This has been implemented as above.

**Comment by pensierinmusica** [comment]
Awesome, thanks!!
