### ISSUE TITLE
Add config option to set default class for dropdowns

### ISSUE THREAD

**Issue by dkravcovs** [IckleChris/jquery-date-dropdowns#7]
This would be useful when working e.g. with bootstrap, when you want to assign existing classes to elements instead of using custom css.

In the config.:

``` js
datePicker.dateDropdowns({
    dropdownClass: 'form-control'
});
```

And in the plugin: 

``` js
buildBaseDropdown: function(type) {
    return $("<select></select>", {
        class: type + ' ' + this.config.dropdownClass,
        name: this.config.submitFieldName + "_[" + type + "]"
    });
}
```

**Comment by jpgnz** [comment]
+1

Have just made the same manual adjustment (thanks @darkalor), but definitely a requirement for anyone using any front end framework like bootstrap.
