### ISSUE TITLE
submitFieldName should not overwrite name if existing input is used

### ISSUE THREAD

**Issue by dkravcovs** [IckleChris/jquery-date-dropdowns#8]
Followup on https://github.com/IckleChris/jquery-date-dropdowns/issues/5

This change introduced a side effect.

``` php
hiddenField = this.$element.attr("type", "hidden")
    .attr("name", this.config.submitFieldName)
    .wrap("<div class=\"" + this.config.wrapperClass + "\"></div>");
```

If the plugin is called on an existing input element, and that input element already has a name attribute that attribute it gets overwritten (i.e. it currently sets it to default value of submitFieldName - 'data'). This is not good behavior, since name attributes are used to build post data and this can break forms.

IMHO it could work like this:
- input has name, no submitFieldName => keep input name
- input has name, submitFieldName is set => use submitFieldName
- input has no name, no submitFieldName => default value of submitFieldName ('date')

**Comment by petruseugene** [comment]
Agree with you, have the same problem.
